---
Metadata:
  TemplateId: "arn:aws:cloudformation:ap-south-1:119391704005:generatedTemplate/713bf048-80f7-4f41-8891-a39b158a9e61"
Resources:
  S3Bucket00integrationframeworktarget00bHB5z:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "integrationframeworktargetdemo1"
      CorsConfiguration:
        CorsRules:
        - MaxAge: 3000
          AllowedMethods:
          - "GET"
          - "POST"
          - "PUT"
          AllowedOrigins:
          - "*"
          AllowedHeaders:
          - "*"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
      LoggingConfiguration:
        TargetObjectKeyFormat:
          PartitionedPrefix:
            PartitionDateSource: "EventTime"
        DestinationBucketName:
          Ref: "S3Bucket00integrationframework00zXMGt"
        LogFilePrefix: "DataQuality/"
  S3BucketPolicy00integrationframeworktarget00Il9yW:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::BucketPolicy"
    DeletionPolicy: "Retain"
    Properties:
      Bucket:
        Ref: "S3Bucket00integrationframeworktarget00bHB5z"
      PolicyDocument:
        Version: "2008-10-17"
        Statement:
        - Condition:
            StringEquals:
              aws:SourceAccount: "119391704005"
          Resource:
          - "arn:aws:s3:::integrationframeworktargetdemo1"
          - "arn:aws:s3:::integrationframeworktargetdemo1/*"
          Action:
          - "s3:PutObject"
          - "s3:AbortMultipartUpload"
          - "s3:ListMultipartUploadParts"
          - "s3:ListBucketMultipartUploads"
          - "s3:GetBucketAcl"
          - "s3:PutObjectAcl"
          Effect: "Allow"
          Principal:
            Service: "appflow.amazonaws.com"
          Sid: "AllowAppFlowDestinationActions"
  S3BucketPolicy00integrationframework00aUJiw:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::BucketPolicy"
    DeletionPolicy: "Retain"
    Properties:
      Bucket:
        Ref: "S3Bucket00integrationframework00zXMGt"
      PolicyDocument:
        Version: "2008-10-17"
        Statement:
        - Condition:
            StringEquals:
              aws:SourceAccount: "119391704005"
          Resource:
          - "arn:aws:s3:::integrationframeworkdemo1"
          - "arn:aws:s3:::integrationframeworkdemo1/*"
          Action:
          - "s3:ListBucket"
          - "s3:GetObject"
          Effect: "Allow"
          Principal:
            Service: "appflow.amazonaws.com"
          Sid: "AllowAppFlowSourceActions"
        - Condition:
            StringEquals:
              aws:SourceAccount: "119391704005"
          Resource: "arn:aws:s3:::integrationframeworkdemo1/*"
          Action: "s3:PutObject"
          Effect: "Allow"
          Principal:
            Service: "logging.s3.amazonaws.com"
          Sid: "S3PolicyStmt-DO-NOT-MODIFY-1710402484452"
  S3Bucket00integrationframework00zXMGt:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "integrationframeworkdemo1"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
